id = "lilypond"
name = "LilyPond"
version = "0.0.5"
schema_version = 1
authors = ["Nathan Whetsell <nathan.whetsell@gmail.com>"]
description = "LilyPond syntax highlighting in Zed"
repository = "https://github.com/nwhetsell/lilypond-zed-extension"

[grammars.lilypond]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond"
commit = "1e607230b4c57d72584822fdd1d844b9d7766b44"

[grammars.lilypond_scheme]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond-scheme"
commit = "c9c3b9e74beb05cc5296f48bd3469b2e6dbf6055"
