id = "lilypond"
name = "LilyPond"
version = "0.0.7"
schema_version = 1
authors = ["Nathan Whetsell <nathan.whetsell@gmail.com>"]
description = "LilyPond syntax highlighting in Zed"
repository = "https://github.com/nwhetsell/lilypond-zed-extension"

[grammars.lilypond]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond"
commit = "5e7f4dd653a0a35f6cfed28b7cc0a24272f75a60"

[grammars.lilypond_scheme]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond-scheme"
commit = "463ef13a48b88feb055980117d70df547d31cf47"
