id = "lilypond"
name = "LilyPond"
version = "0.0.4"
schema_version = 1
authors = ["Nathan Whetsell <nathan.whetsell@gmail.com>"]
description = "LilyPond syntax highlighting in Zed"
repository = "https://github.com/nwhetsell/lilypond-zed-extension"

[grammars.lilypond]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond"
commit = "c8eee202411d7e53971fed4344b1f15219d1e655"

[grammars.lilypond_scheme]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond-scheme"
commit = "2a7a96a0cfba8f6106df821265ae67aa5ab3ce45"
