id = "lilypond"
name = "LilyPond"
version = "0.0.9"
schema_version = 1
authors = ["Nathan Whetsell <nathan.whetsell@gmail.com>"]
description = "LilyPond syntax highlighting in Zed"
repository = "https://github.com/nwhetsell/lilypond-zed-extension"

[grammars.lilypond]
repository = "https://github.com/nwhetsell/zed-tree-sitter-lilypond"
commit = "c8f64ae75f130225bd7cff46eb464f08e7a283e6"

[grammars.lilypond_scheme]
repository = "https://github.com/nwhetsell/zed-tree-sitter-lilypond-scheme"
commit = "ffb662311084b86087ebb474a79b7f1f7ed2541f"
