id = "lilypond"
name = "LilyPond"
version = "0.0.6"
schema_version = 1
authors = ["Nathan Whetsell <nathan.whetsell@gmail.com>"]
description = "LilyPond syntax highlighting in Zed"
repository = "https://github.com/nwhetsell/lilypond-zed-extension"

[grammars.lilypond]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond"
commit = "d88b342d16efab6057631aa6dc95158f08c8237a"

[grammars.lilypond_scheme]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond-scheme"
commit = "6ba44da41e2337e88c7e41b4c7ce6f5c4b9fdbe9"
