id = "lilypond"
name = "LilyPond"
version = "0.0.2"
schema_version = 1
authors = ["Nathan Whetsell <nathan.whetsell@gmail.com>"]
description = "LilyPond syntax highlighting in Zed"
repository = "https://github.com/nwhetsell/lilypond-zed-extension"

[grammars.lilypond]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond"
commit = "5685298e084ac001fdbe9f38b5554ded897d056c"

[grammars.lilypond_scheme]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond-scheme"
commit = "5281b8bab7ce12bc06219b09fcfcefea18952dfb"
